
language: python
python:
  - 3.7
services:
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t joffreybvn/api-mathieu:latest .

deploy:
  provider: script
  script:
    docker push joffreybvn/api-mathieu:latest;
  on:
    branch: main